### ISSUE TITLE
Add [minSize] property on <as-split-area>

### ISSUE THREAD

**Issue by punkJD** [bertrandg/angular-split#124]
I have the need in a project i'm involved, to block the drag to assure the top split area has always at least a minimum stipulated size.
I just want to ask if you are working on the min size feature or if i should just do a pull request with it.

**Comment by bertrandg** [comment]
There are multiple wanted features related to sizes (min/max, locked, pixel, wildcard,..) and I will work on it so don't do pull request now please because these features have to be think together (if I decide to add them all).

But currently, before new features, my main focus is:
- add as many cypress e2e tests to be sure not breaking things later.
- fix some browser specific issue (edge/ie11/safari).
- fix issue about devicePixelRatio.

**Comment by bertrandg** [comment]
Check #131 for what's coming.
