### ISSUE TITLE
Add info on readme about new split 2.0.0 requirements

### ISSUE THREAD

**Issue by jmesa-sistel** [bertrandg/angular-split#132]
Hello
Usually I use a shared module to export AngularSplitModule  since your changes about CustomEventManager the shared module is not working anymore.
I've noticed that I need to add AngularSplitModule in app.module.ts and also in all modules that use AngularSplit, I think this change is related to CustomEventManager. 
In 2.0.0-beta4 I can use a shared module but in beta5 and later I need to add AngularSplitModule in AppModule and all modules that use AngularSplit.
I've spent several hours try to find my problem, so I think it is a good idea to add a warning in the main page explaining this requirement to get AngularSplit working in different modules.
Regards

**Comment by bertrandg** [comment]
Hi,
thanks for your time investigating and reporting it,
I will first try to 'solve' it to make it work as before if I can.

Maybe my module declaration is not right, I've seen this one adding `providers` inside `forRoot()` instead of `@NgModule` annotation:
https://github.com/valor-software/ngx-bootstrap/blob/master/src/alert/alert.module.ts
https://github.com/bertrandg/angular-split/blob/master/projects/angular-split/src/lib/module.ts

Do you have others public module in your shared module working as `angular-split@2.0.0-beta.4` to help me?

**Comment by gbenthomas** [comment]
I believe this is an angular issue: angular/angular#19874

Ran into the same problem recently with Hammerjs and Angular Material (referenced in that issue too).

On a side note, how big of a performance gain does running the click/mousedown/touchdown events outsize angular zone bring? It looks like the actual drag events (mousemove/touchmove) are already running outside the angular zone.

**Comment by bertrandg** [comment]
Thanks for the link @gbenthomas 

About event listeners, yes, mousemove/touchmove are already outside zone (i set them manually with `renderer.listen()`). 
And for click/mousedown/touchdown events, I was annoyed to trigger whole app change detection multiple times just because gutter is moved so I did like that but the performance gain is not giant.

**Comment by rodries** [comment]
@bertrandg 
Tested and working flawlessly 
Now I import AngularSplitModule.forRoot() in AppModule and AngularSplitModule in my shared module and all modules can use your split library through the shared module.
Good work

**Comment by gbenthomas** [comment]
@bertrandg Thanks for the update. This works but now we're adding AngularSplitModule to the main bundle and losing the benefits of lazy loading. This library is small but it can be a problem when every kb matters for the initial load on mobile devices for example. 

Is losing the ability to lazy load this module worth it compared to the minor performance gain of not running change detection on those events? If so, can we create a new issue to support lazy loading once the Angular issue is fixed? Thanks for all your hard work! 

Screenshot of angular-split in main module using webpack-bundle-analyzer:
![image](https://user-images.githubusercontent.com/35936423/50360717-951b4800-0526-11e9-9315-991f281fffce.png)

**Comment by gbenthomas** [comment]
Or maybe another option would be to make it configurable to use the event manager plugin or not and let the developers make the tradeoff?

**Comment by bertrandg** [comment]
@gbenthomas 
I'm working on next version `3.x` and I've decided to remove some extra stuff I added (`CustomEventManager` and `Subscriber` instead of simple `EventEmitter` for outputs) to avoid some change detection runs. 
I think drawbacks side were at least as much as gains so.. why going against framework.

So it's gonna work again as you want for lazy loaded module!

**Comment by bertrandg** [comment]
You can test new lighter version with `3.0.0-beta.9`! :)

**Comment by gbenthomas** [comment]
@bertrandg Works well now. Thanks!
