### ISSUE TITLE
dragProgress$ not emitting an Observable

### ISSUE THREAD

**Issue by JohannBillar** [bertrandg/angular-split#134]
Trying to implement a min-size for as-split-area. I'm having a problem with ***dragProgress$.*** It's not emitting an observable value for me.  I can't get this code to work:

``` 
this.x = this.splitEl.dragProgress$;

{{ x | async | json }}
```

Then, when I try the same with the dragStart Observable, it does emit a value on dragStart

```
this.x = this.splitEl.dragStart;

{{ x | async | json }}
```

Any ideas on what I'm doing wrong?

**Comment by bertrandg** [comment]
Hi @JohannBillar,

I added `dragProgress$` to allow synchronized split without triggering change detection too frequently like this example:
[demo](https://bertrandg.github.io/angular-split/#/examples/sync-split) / [source](https://github.com/bertrandg/angular-split/blob/master/src_app/app/component/examples/sync.route.component.ts)

So it's running outside zone by design, but your are right I need to add it to the doc. 
Check this demo to see it working as you want:
https://stackblitz.com/edit/angular-duzjbv?file=src%2Fapp%2Fapp.component.ts

But for the `minSize` feature, I'm working on it (but no time estimation yet):
https://stackblitz.com/edit/angular-j45ncr?file=src%2Fapp%2Fapp.component.css

**Comment by JohannBillar** [comment]
Thanks @bertrandg! Go it to work.
