### ISSUE TITLE
Gutterclick on touch devices

### ISSUE THREAD

**Issue by mavogt** [bertrandg/angular-split#145]
gutterClick event seems not to work anymore on touch devices.
This worked in older releases.

**Comment by bertrandg** [comment]
hi,
Can you specify the version you use currently where it's not working and an older where it worked please.

**Comment by mavogt** [comment]
Currently I use the version 2.0.1.
I can't exactly say you the version where it still worked. But I have the code of an old version from february 2018 where it worked.

**Comment by bertrandg** [comment]
Thanks, 
can you give the mobile OS/browser where it worked and then stopped working please.
I will take a look.

**Comment by mavogt** [comment]
I tested it with the newest chrome version on android.

**Comment by bertrandg** [comment]
I've just published `angular-split@3.0.0-beta.9` which solve mobile `(gutterClick)` event not fired and add `(gutterDblClick)` event.

Check demo there:
https://stackblitz.com/edit/angular-xztkig?file=src%2Fapp%2Fapp.module.ts

Note that I'm not gonna update 2.x because I have changed too many things to fix this.. but `3.0.0` comes soon.
