### ISSUE TITLE
Custom area sizing calculations/functions.

### ISSUE THREAD

**Issue by StefanKoenigMUC** [bertrandg/angular-split#148]
Hi all,

in one of angular-split's forked a very interesting feateure came up: Custom classes for dynamic calculation of area sizes.

https://github.com/steven-coding/ng-split-areas/tree/master/src/interface/calculation

Would it be possible, to include a feature like this into angular-split as well? [I'm using the fork at the moment, but i would like to get back into a non-forked / updated version].

Thanks for your great work!

**Comment by bertrandg** [comment]
Hi @StefanKoenigMUC ,
That's interesting, what's your usecase for this?

Because I don't see other than minSize/maxSize scenarios.. 
And I'm adding it to `3.0.0` which is coming really soon (curently fully functional `3.0.0-beta.9` already available).

Check this for more details about the new API: https://github.com/bertrandg/angular-split/issues/131

**Comment by StefanKoenigMUC** [comment]
It's a bit hard to explain (as I may not be allowed to share some screenshots, I have to stay in textual form).

Basically, we're using those split panes as navigation panes. Due to some space constraints, some of those tiles may be collapsed (menu items -> hidden; just descriptive vertical text). Collapsing may also be user-triggered. 

Also, different areas may have different fixed widths (calculation of necessary width is done by the component itself). 

I'll have a look, if i can provide some screenshots / create a reduced working example.

**Comment by bertrandg** [comment]
Version `3.0.0` has just been released with min & max sizes options.
Custom area sizing calculations is not planned for this library...
