### ISSUE TITLE
Build failed with 'Metadata version mismatch for module '

### ISSUE THREAD

**Issue by vincent-cm** [bertrandg/angular-split#63]
Metadata version mismatch for module ~/node_modules/angular-split/angular-split.d.ts, found version 4, expected 3

Does it not support angular4 any more?

**Comment by bertrandg** [comment]
Weird, 
I didn't try with angular-cli but using System.js & UMD module works good using angular `4.4.4` & angular-split `0.2.6`:
https://plnkr.co/edit/PGKOzk?p=preview

Any more info about your error?

**Comment by tflavin** [comment]
Here is the stack trace that I get:

`ERROR in Error: Metadata version mismatch for module ~/node_modules/angular-split/angular-split.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (~\node_modules\@angular\compiler\bundles\compiler.umd.js:25616:34)
    at StaticSymbolResolver._createSymbolsOf (~\node_modules\@angular\compiler\bundles\compiler.umd.js:25404:46)
    at StaticSymbolResolver.getSymbolsOf (~\node_modules\@angular\compiler\bundles\compiler.umd.js:25385:14)
    at ~\node_modules\@angular\compiler\bundles\compiler.umd.js:24241:30
    at Array.forEach (native)
    at extractProgramSymbols (~\node_modules\@angular\compiler\bundles\compiler.umd.js:24240:79)
    at AotCompiler.analyzeModulesAsync (~\node_modules\@angular\compiler\bundles\compiler.umd.js:23796:47)
    at CodeGenerator.codegen (~\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (~\node_modules\@angular\compiler-cli\src\ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (~\node_modules\@ngtools\webpack\src\plugin.js:386:44)`

**Comment by bertrandg** [comment]
Give me cli version & angular version please, I will test it.

**Comment by jackytse** [comment]
I got this error too. 
angular version: 4.3.2
cli version: 1.4.2

**Comment by bertrandg** [comment]
Thanks @jackytse 

I've reproduce it and sadly, this is due to a new format used for the metadata:
https://github.com/michaelbromley/ngx-pagination/issues/210#issuecomment-338571373
I love angular but bundling a library for it is really painful!

So yes, versions after `0.2.3` are only for angular v5.x.

**Comment by jainmitesh09** [comment]
I am getting the same error with following versions

"@angular/cli": "^1.3.2"
"@angular/core": "^4.3.3"
"angular-split": "^0.2.2"

I was using 0.2.2 with angular 4.x.

**Comment by mxtommy** [comment]
Just some advice (from a newbie so maybe I'm wrong, if so forgive me!), but breaking changes (like not supporting angular 4) should likely increase the major version level, so that people who have "^0.2.2" wont get bitten by suddenly failing code  :)

At any rate, thanks for your library!

**Comment by bertrandg** [comment]
Yes you're right, following semver I should have release a new major version but it wasn't an expected behavior (I was thinking that updating bundling tools wouldn't impact). I didn't test enought.. 
Your idea is good but, honestly, in relation to the small audience of this library, I don't want to spent more time on this, but will remember it for next time.
And 1.0.0 is already in the pipepline (published `1.0.0-beta.1` today) with a refactor allowing more things! ;)

**Comment by bertrandg** [comment]
@jainmitesh09 I've just test with your exact versions and it works properly.

angular/cli: 1.3.2
angular/core: 4.3.3
angular-split: 0.2.2

Please clear your cache, remove your `node_modules` and `npm i`, it sould works.
And be sure to have angular-split `<=0.2.3` if you are using angular `<5.0.0`.

**Comment by bertrandg** [comment]
Just published `0.2.7` which is a copy of `0.2.3` (so compatible with angular 4.x). ;)
Version `1.0.0` need angular >= 5.0.0.
