### ISSUE TITLE
useTransition does not appear to be working on IE11

### ISSUE THREAD

**Issue by mconner** [bertrandg/angular-split#88]
The useTransition does not appear to be working on IE11.
[https://stackblitz.com/edit/angular-r3ntnw](https://stackblitz.com/edit/angular-r3ntnw)
(UPDATED: sorry, the url, itself, wasn't set in the link. Fixed)

**Comment by thisiszoaib** [comment]
Any update on the fix for this?

**Comment by guguji5** [comment]
try [http://angular-splitter.guguji5.top](http://angular-splitter.guguji5.top) , it works in IE.

**Comment by bertrandg** [comment]
@guguji5 Just tried you website:
Edge40 > Works without transition
IE11 > Error at app start
Chrome > works with transition

I've seen, looking at your code, you are using `flex-basis: calc( X% - Ypx )` and `transition-property:flex;` on areas. 
I use `transition: flex-basis .3s;` which is an equivalent so I'm curious if it's really working on IE11 viewing what I've seen down.

@mconner @thisiszoaib 
I've investigate about it and found that it's a:
- IE9-11: [Known issue](https://stackoverflow.com/questions/19776959/transition-not-animating-in-ie9-11-when-using-calc), [bugtracker](https://connect.microsoft.com/IE/feedback/details/733978/css-animation-dont-accept-calc-as-property-values) is dead now but the guy tells it has been closed as `Resolved as Postponed` so never solved.
Seen [there too](https://caniuse.com/#search=calc) inside `known issues (12)` tab: "IE11 does not support transitioning values set with calc()".. 😭
- Edge: [Known issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/105834/) opened in 2014 and not resolved! 😭

Because transitions are for estethic purpose, I will not make fondamental changes (use `flex-basis: calc();` is the library base operation) to support an old/semi-dead browser so I close this issue because there is another one for Edge https://github.com/bertrandg/angular-split/issues/103.
It will never works for IE, sorry..
